apiVersion: v1
kind: Service
metadata:
  name: minintel-service
  namespace: minintel
  labels:
    app: minintel-node
spec:
  selector:
    app: minintel-node
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer  # Change to ClusterIP for internal service
