# Machine Intelligence Node - Default Configuration
# Defines core settings for training, inference, and system performance.

system:
  device: "cuda"  # Options: "cuda", "cpu"
  num_threads: 8  # Number of CPU threads for data loading
  seed: 42  # Random seed for reproducibility
  logging:
    enabled: true
    log_dir: "logs/"
    level: "info"  # Options: "debug", "info", "warning", "error"

model:
  architecture: "transformer"
  model_path: "models/checkpoint.pth"
  input_size: 512
  output_size: 10
  dropout: 0.1

training:
  batch_size: 32
  epochs: 50
  learning_rate: 0.001
  optimizer: "adam"  # Options: "sgd", "adam", "adamw"
  scheduler:
    enabled: true
    step_size: 10
    gamma: 0.5
  checkpointing:
    enabled: true
    save_interval: 5
    checkpoint_dir: "models/checkpoints/"

inference:
  batch_size: 16
  max_length: 128
  temperature: 0.8  # Sampling temperature for generative models
  top_k: 40  # Top-K sampling
  top_p: 0.9  # Top-P (nucleus) sampling

data:
  dataset_path: "data/dataset.csv"
  validation_split: 0.2
  shuffle: true
  num_workers: 4

web:
  api_enabled: true
  api_host: "0.0.0.0"
  api_port: 8080
  websocket_enabled: true
  websocket_port: 9090

deployment:
  docker:
    enabled: true
    image_name: "minintel-node"
  kubernetes:
    enabled: false
    namespace: "minintel"
