# Machine Intelligence Node - Logging Configuration
# Defines structured logging settings for training, inference, and system monitoring.

logging:
  version: 1
  disable_existing_loggers: false

  formatters:
    detailed:
      format: "[%(asctime)s] [%(levelname)s] %(name)s: %(message)s"
    simple:
      format: "[%(levelname)s] %(message)s"

  handlers:
    console:
      class: logging.StreamHandler
      level: "INFO"
      formatter: "simple"
      stream: "ext://sys.stdout"

    file:
      class: logging.FileHandler
      level: "DEBUG"
      formatter: "detailed"
      filename: "logs/machine_intelligence.log"
      mode: "a"

    rotating_file:
      class: logging.handlers.RotatingFileHandler
      level: "DEBUG"
      formatter: "detailed"
      filename: "logs/machine_intelligence_rotating.log"
      maxBytes: 10485760  # 10 MB per file
      backupCount: 5

  root:
    level: "DEBUG"
    handlers: ["console", "file", "rotating_file"]

  loggers:
    model_training:
      level: "INFO"
      handlers: ["console", "file"]
      propagate: false

    inference:
      level: "WARNING"
      handlers: ["console", "file"]
      propagate: false

    system:
      level: "DEBUG"
      handlers: ["console", "rotating_file"]
      propagate: false
